[package]
name = "task_017_number_letter_counts"
version = "0.1.0"
authors = ["guitarman <guitarman78@freenet.de>"]

[dependencies]
termion = "1"
unicode-segmentation = "0.1.2"
numbers = "0.1.2"
regex = "1"
